#!/usr/bin/env bash
# ScrapSaver local production stack (IT_4, workstream P). Runs everything on this Mac:
#
#   SpacetimeDB  127.0.0.1:3000   `spacetime start` (database `scrap`)
#   SAM 2.1      127.0.0.1:8790   vision/sam/worker.py   (.venv, MPS)
#   backend      127.0.0.1:8787   NODE_ENV=production SERVE_FRONTEND=1 (serves frontend/dist)
#
# A Cloudflare Tunnel maps https://<your domain> to the backend (docs/deploy.md).
# Depth Anything V2 was removed (2026-10-04): this script no longer starts a depth
# worker, but `down` still stops one it started earlier (deploy/.run/depth.pid).
#
#   deploy/local.sh up        build + start whatever is not already running, then health-check
#   deploy/local.sh down      stop ONLY the processes this script started (pidfiles; incl. a legacy depth worker)
#   deploy/local.sh status    show each service: healthy?, who owns it
#   deploy/local.sh restart   down + up
#   deploy/local.sh smoke     deploy/smoke.mjs against this stack, with the stack's ingest token
#   deploy/local.sh seed --live-dinner   backend/scripts/seed.mjs against this stack (demo menus)
#
# Idempotent: a service whose port already answers its health check is reused
# (and never stopped by `down`, because there is no pidfile for it). A port that
# is taken but unhealthy is reported, never killed. State lives in deploy/.run/
# (gitignored): <name>.pid, logs/<name>.log, local-secrets.env.
# Nothing is ever killed by name or port: only pids from our own pidfiles whose
# command line still matches the service.
#
# Environment (all optional):
#   SCRAP_ENV_FILE   secrets file to load (default <repo>/.env; never printed)
#   SCRAP_VENV       Python venv with torch + sam2 (default <repo>/.venv)
#   SCRAP_RUN_DIR    state dir (default <repo>/deploy/.run); e.g. a git worktree reusing the main checkout's stack
#   API_PORT / API_HOST       backend bind (default 8787 / 127.0.0.1)
#   SAM_PORT / STDB_PORT      (default 8790 / 3000)
#   SKIP_BUILD=1     do not rebuild backend/frontend before starting the backend
#   HEALTH_TIMEOUT_ML  seconds to wait for the SAM worker (default 300; first run downloads weights)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN="${SCRAP_RUN_DIR:-$REPO/deploy/.run}"
LOGS="$RUN/logs"
SECRETS="$RUN/local-secrets.env"
ENV_FILE="${SCRAP_ENV_FILE:-$REPO/.env}"
VENV="${SCRAP_VENV:-$REPO/.venv}"
API_PORT="${API_PORT:-8787}"
API_HOST="${API_HOST:-127.0.0.1}"
SAM_PORT="${SAM_PORT:-8790}"
STDB_PORT="${STDB_PORT:-3000}"
HEALTH_TIMEOUT_ML="${HEALTH_TIMEOUT_ML:-300}"
SERVICES="spacetimedb sam api"
# Removed services that `down` (and `status`) still handle through their pidfiles.
LEGACY_SERVICES="depth"
LEGACY_DEPTH_PORT=8791

mkdir -p "$LOGS"

say()  { printf '[local] %s\n' "$*"; }
warn() { printf '[local] WARNING: %s\n' "$*" >&2; }
die()  { printf '[local] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- per-service facts

port_of() {
  case "$1" in
    spacetimedb) echo "$STDB_PORT" ;; sam) echo "$SAM_PORT" ;;
    depth) echo "$LEGACY_DEPTH_PORT" ;; api) echo "$API_PORT" ;;
  esac
}

# Substring that must appear in a pid's command line before we signal it
# (guards against a recycled pid belonging to something else). depth = the
# removed Depth Anything V2 worker, kept so `down` can still stop it.
cmd_pattern_of() {
  case "$1" in
    spacetimedb) echo "spacetime" ;; sam) echo "vision/sam/worker.py" ;;
    depth) echo "vision/depth/worker.py" ;; api) echo "dist/backend/src/server.js" ;;
  esac
}

healthy() {
  local port; port="$(port_of "$1")"
  case "$1" in
    spacetimedb) curl -fsS -m 3 -o /dev/null "http://127.0.0.1:$port/v1/ping" 2>/dev/null ;;
    sam|depth)   curl -fsS -m 3 "http://127.0.0.1:$port/health" 2>/dev/null | grep -Eq '"ok": ?true' ;;
    api)         curl -fsS -m 3 "http://127.0.0.1:$port/api/health" 2>/dev/null | grep -Eq '"ok": ?true' ;;
  esac
}

listening_pid() { lsof -nP -iTCP:"$1" -sTCP:LISTEN -t 2>/dev/null | head -1 || true; }

# pid from our pidfile if that process is alive and still looks like the service.
our_pid() {
  local f="$RUN/$1.pid" pid
  [ -f "$f" ] || return 1
  pid="$(cat "$f")"
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null && ps -p "$pid" -o command= | grep -q "$(cmd_pattern_of "$1")"; then
    echo "$pid"; return 0
  fi
  rm -f "$f"   # stale
  return 1
}

# ---------------------------------------------------------------- environment

load_env() {
  # Generated once, mode 600, never printed. .env (loaded after) wins.
  if [ ! -f "$SECRETS" ]; then
    ( umask 077
      { echo "# generated by deploy/local.sh for the local production stack; never commit"
        echo "SCRAP_INGEST_TOKEN=$(openssl rand -hex 32)"
        echo "SCRAP_ADMIN_PASSCODE=$(openssl rand -hex 6)"
        echo "SESSION_SECRET=$(openssl rand -hex 32)"
      } > "$SECRETS" )
    say "generated local auth secrets in deploy/.run/local-secrets.env (admin passcode: see that file)"
  fi
  set -a
  # shellcheck disable=SC1090
  . "$SECRETS"
  if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
  else
    warn "no env file at $ENV_FILE: backend runs without Gemini/R2/SpacetimeDB secrets"
  fi
  set +a
  # Stack wiring always points at the local services.
  export SAM_WORKER_URL="http://127.0.0.1:$SAM_PORT"
  export SPACETIMEDB_URI="${SPACETIMEDB_URI:-http://127.0.0.1:$STDB_PORT}"
}

# ---------------------------------------------------------------- start helpers

# launch <name> <dir> <cmd...>: detached (own session), logs appended, pidfile written.
launch() {
  local name="$1" dir="$2"; shift 2
  local log="$LOGS/$name.log"
  printf '\n===== %s start %s =====\n' "$name" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$log"
  ( cd "$dir"
    perl -MPOSIX -e 'POSIX::setsid(); exec @ARGV or die "exec failed: $!\n"' "$@" >> "$log" 2>&1 < /dev/null &
    echo $! > "$RUN/$name.pid" )
}

wait_healthy() {
  local name="$1" timeout="$2" waited=0 pid
  pid="$(cat "$RUN/$name.pid" 2>/dev/null || true)"
  while ! healthy "$name"; do
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$RUN/$name.pid"
      warn "$name exited during startup; last log lines:"
      tail -n 25 "$LOGS/$name.log" >&2 || true
      return 1
    fi
    if [ "$waited" -ge "$timeout" ]; then
      warn "$name not healthy after ${timeout}s (still running as pid $pid; see deploy/.run/logs/$name.log)"
      return 1
    fi
    sleep 2; waited=$((waited + 2))
  done
  say "$name healthy on :$(port_of "$name") (${waited}s)"
}

# Returns 0 when the caller should start the service, 1 when it is already handled.
needs_start() {
  local name="$1" port pid
  port="$(port_of "$name")"
  if pid="$(our_pid "$name")"; then
    if healthy "$name"; then say "$name already running (ours, pid $pid)"; return 1; fi
    warn "$name (ours, pid $pid) is not healthy yet; not starting a second copy"; return 1
  fi
  pid="$(listening_pid "$port")"
  if [ -n "$pid" ]; then
    if healthy "$name"; then
      say "$name: reusing the healthy service already on :$port (pid $pid, not started by this script; 'down' leaves it alone)"
    else
      warn "$name: port $port is taken by pid $pid, which fails the health check. Not touching it."
      STACK_OK=0
    fi
    return 1
  fi
  return 0
}

python_bin() {
  [ -x "$VENV/bin/python" ] || die "no Python venv at $VENV (set SCRAP_VENV; see vision/sam/README.md)"
  echo "$VENV/bin/python"
}

start_spacetimedb() {
  needs_start spacetimedb || return 0
  command -v spacetime >/dev/null || die "spacetime CLI not found (https://spacetimedb.com/install)"
  launch spacetimedb "$REPO" spacetime start --listen-addr "127.0.0.1:$STDB_PORT" --non-interactive
  wait_healthy spacetimedb 60 || STACK_OK=0
}

start_sam() {
  needs_start sam || return 0
  local py; py="$(python_bin)"
  # D8 decision: no supervisor. caffeinate -i stops idle sleep from freezing
  # SAM (lid close still sleeps; keep the lid open or use clamshell mode).
  # If SAM exits, captures fail with a retryable SEGMENTATION_UNAVAILABLE and
  # 'deploy/local.sh up' restarts it. Set SCRAP_CAFFEINATE=0 to disable.
  local keep=(); if [ "${SCRAP_CAFFEINATE:-1}" = 1 ] && command -v caffeinate >/dev/null; then keep=(caffeinate -i); fi
  launch sam "$REPO" env SAM_HOST=127.0.0.1 WORKER_HOST=127.0.0.1 SAM_PORT="$SAM_PORT" \
    PYTORCH_ENABLE_MPS_FALLBACK=1 ${keep[@]+"${keep[@]}"} "$py" vision/sam/worker.py
  wait_healthy sam "$HEALTH_TIMEOUT_ML" || STACK_OK=0
}

build_app() {
  local log="$LOGS/build.log"
  say "building data/vision/analytics/backend and frontend (log: deploy/.run/logs/build.log)"
  printf '\n===== build %s =====\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$log"
  local pkg
  for pkg in data vision analytics backend frontend; do
    if [ ! -d "$REPO/$pkg/node_modules" ]; then
      (cd "$REPO/$pkg" && npm ci --no-audit --no-fund) >> "$log" 2>&1 || die "npm ci failed in $pkg (see build log)"
    fi
  done
  (cd "$REPO/backend" && npm run build) >> "$log" 2>&1 || die "backend build failed (see build log)"
  (cd "$REPO/frontend" && npm run build) >> "$log" 2>&1 || die "frontend build failed (see build log)"
}

start_api() {
  needs_start api || return 0
  [ "${SKIP_BUILD:-0}" = 1 ] || build_app
  [ -f "$REPO/backend/dist/backend/src/server.js" ] || die "backend is not built (run without SKIP_BUILD)"
  # cwd backend/ so the local-dev object store (.local-storage) stays where `npm start` puts it.
  launch api "$REPO/backend" env NODE_ENV=production SERVE_FRONTEND=1 \
    FRONTEND_DIST="$REPO/frontend/dist" PORT="$API_PORT" HOST="$API_HOST" \
    node dist/backend/src/server.js
  wait_healthy api 90 || STACK_OK=0
}

report_api() {
  local base="http://127.0.0.1:$API_PORT" code ctype
  code="$(curl -s -m 10 -o /dev/null -w '%{http_code}' "$base/api/ready" || true)"
  case "$code" in
    200) say "api /api/ready: 200 (database, storage and workers reachable)" ;;
    404) warn "api /api/ready: 404 (this backend has no readiness route yet)" ;;
    *)   warn "api /api/ready: $code (curl $base/api/ready for details)" ;;
  esac
  ctype="$(curl -s -m 5 -o /dev/null -w '%{content_type}' "$base/" || true)"
  case "$ctype" in
    text/html*) say "dashboard served at $base/" ;;
    *) warn "the backend on :$API_PORT does not serve the dashboard (no SERVE_FRONTEND support, or an older dev backend is being reused). Use 'cd frontend && npm run dev' meanwhile." ;;
  esac
}

# ---------------------------------------------------------------- commands

cmd_up() {
  local pid
  STACK_OK=1
  load_env
  start_spacetimedb
  if healthy spacetimedb; then
    local db="${SPACETIMEDB_MODULE:-scrap}"
    if ! curl -fsS -m 5 -o /dev/null "http://127.0.0.1:$STDB_PORT/v1/database/$db" 2>/dev/null; then
      warn "SpacetimeDB has no database '$db'. Publish it once (db/README.md), then rerun."
    fi
  fi
  start_sam
  if pid="$(our_pid depth)"; then
    warn "a Depth Anything V2 worker started earlier by this script is still running (pid $pid, :$LEGACY_DEPTH_PORT). Depth was removed; stop it with: deploy/local.sh down (then up)"
  fi
  start_api
  healthy api && report_api
  cmd_status
  if [ "$STACK_OK" = 1 ]; then
    say "stack up. Smoke test: node deploy/smoke.mjs http://127.0.0.1:$API_PORT"
  else
    die "stack is not fully healthy (see warnings above)"
  fi
}

cmd_down() {
  local name pid stopped=0
  for name in api $LEGACY_SERVICES sam spacetimedb; do
    if pid="$(our_pid "$name")"; then
      say "stopping $name (pid $pid)"
      kill -TERM "$pid" 2>/dev/null || true
      for _ in $(seq 1 15); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
      if kill -0 "$pid" 2>/dev/null; then warn "$name did not exit after 15s; sending KILL"; kill -KILL "$pid" 2>/dev/null || true; fi
      rm -f "$RUN/$name.pid"; stopped=$((stopped + 1))
    fi
  done
  say "stopped $stopped service(s) started by this script; anything else was left running"
}

cmd_status() {
  local name port pid owner health
  printf '%-12s %-6s %-9s %s\n' SERVICE PORT HEALTH OWNER
  for name in $SERVICES; do
    port="$(port_of "$name")"
    if healthy "$name"; then health=healthy; else health=down; fi
    if pid="$(our_pid "$name")"; then owner="local.sh (pid $pid)"
    else
      pid="$(listening_pid "$port")"
      if [ -n "$pid" ]; then owner="external (pid $pid)"; else owner="-"; fi
    fi
    printf '%-12s %-6s %-9s %s\n' "$name" "$port" "$health" "$owner"
  done
  # D7: which build is the running backend? Flag it when the checkout moved on.
  local head running
  head="$(git -C "$REPO" rev-parse HEAD 2>/dev/null || true)"
  running="$(curl -fsS -m 3 "http://127.0.0.1:$API_PORT/api/health" 2>/dev/null | sed -n 's/.*"commit":"\([^"]*\)".*/\1/p')"
  if ! healthy api; then :
  elif [ -z "$running" ]; then echo "backend build: unknown (old build without commit info): restart needed"
  elif [ "$running" = "$head" ]; then echo "backend build: ${running:0:9} (matches checkout)"
  else echo "backend build: ${running:0:9}, checkout is ${head:0:9}: restart needed ('deploy/local.sh restart')"
  fi
  for name in $LEGACY_SERVICES; do
    if pid="$(our_pid "$name")"; then
      printf '%-12s %-6s %-9s %s\n' "$name" "$(port_of "$name")" removed "local.sh (pid $pid): no longer used; 'deploy/local.sh down' stops it"
    fi
  done
}

# Run with the same effective secrets as the backend this script starts
# (.env wins over deploy/.run/local-secrets.env), so tokens never mismatch.
cmd_smoke() {
  load_env
  node "$REPO/deploy/smoke.mjs" "http://127.0.0.1:$API_PORT" "$@"
}

cmd_seed() {
  load_env
  [ -f "$REPO/data/dist/data/src/index.js" ] || die "data package not built (run 'deploy/local.sh up' first)"
  (cd "$REPO/backend" && API_URL="http://127.0.0.1:$API_PORT" node scripts/seed.mjs "$@")
}

case "${1:-}" in
  up) cmd_up ;;
  smoke) shift; cmd_smoke "$@" ;;
  seed) shift; cmd_seed "$@" ;;
  down) cmd_down ;;
  status) cmd_status ;;
  restart) cmd_down; cmd_up ;;
  *) echo "usage: deploy/local.sh {up|down|status|restart|smoke [--strict]|seed [--live-dinner]}" >&2; exit 2 ;;
esac
