// GENERATED by data/scripts/generate-factors.mjs. Do not edit by hand.
// Source of truth: menu_waste_factors.csv and menu_nutrition_factors.csv
// (repo root). Regenerate with `npm run factors` in data/.

import type { NutritionFactor, WasteFactor } from '../../contracts/types.js';

/** Plate-photo text and label metadata per factor row (not part of the score). */
export interface WasteFactorMenuText {
  factorKey: string;
  food: string;
  station: string;
  /** Gemini's visible-components description; null when Gemini had no source for the food. */
  visibleComponents: string | null;
  ingredients: string | null;
  allergens: string | null;
  labelServingG: number | null;
  menuCo2Label: string | null;
}

/** menu_waste_factors.csv rows. Score = 0.19*C + 1.50*W (no nutrition). */
export const WASTE_FACTORS: WasteFactor[] = [
  {
    "factorKey": "broccoli-cheddar-soup",
    "food": "Broccoli Cheddar Soup",
    "station": "Soup",
    "weightGPerCm2": 1.5,
    "kgCo2ePerKg": 4.9,
    "waterM3PerKg": 1.07,
    "impactUsdPerKg": 2.54,
    "largestFactor": "water"
  },
  {
    "factorKey": "baked-boneless-ham",
    "food": "Baked Boneless Ham",
    "station": "Signature Maize",
    "weightGPerCm2": 0.9,
    "kgCo2ePerKg": 12.39,
    "waterM3PerKg": 1.808,
    "impactUsdPerKg": 5.07,
    "largestFactor": "water"
  },
  {
    "factorKey": "oven-roasted-garlic-potatoes",
    "food": "Oven Roasted Garlic Potatoes",
    "station": "Signature Maize",
    "weightGPerCm2": 1.6,
    "kgCo2ePerKg": 0.62,
    "waterM3PerKg": 0.117,
    "impactUsdPerKg": 0.29,
    "largestFactor": "water"
  },
  {
    "factorKey": "baked-sweet-potatoes",
    "food": "Baked Sweet Potatoes",
    "station": "Signature Maize",
    "weightGPerCm2": 2,
    "kgCo2ePerKg": 0.43,
    "waterM3PerKg": 0.028,
    "impactUsdPerKg": 0.12,
    "largestFactor": "carbon"
  },
  {
    "factorKey": "roasted-cauliflower",
    "food": "Roasted Cauliflower",
    "station": "Signature Maize",
    "weightGPerCm2": 1,
    "kgCo2ePerKg": 0.54,
    "waterM3PerKg": 0.13,
    "impactUsdPerKg": 0.3,
    "largestFactor": "water"
  },
  {
    "factorKey": "michigan-farmers-4-bean-stew",
    "food": "Michigan Farmers 4 Bean Stew",
    "station": "24 Carrots",
    "weightGPerCm2": 1.5,
    "kgCo2ePerKg": 0.95,
    "waterM3PerKg": 0.198,
    "impactUsdPerKg": 0.48,
    "largestFactor": "water"
  },
  {
    "factorKey": "farro",
    "food": "Farro",
    "station": "24 Carrots",
    "weightGPerCm2": 1.1,
    "kgCo2ePerKg": 0.75,
    "waterM3PerKg": 0.311,
    "impactUsdPerKg": 0.61,
    "largestFactor": "water"
  },
  {
    "factorKey": "shaved-brussel-sprouts",
    "food": "Shaved Brussel Sprouts",
    "station": "24 Carrots",
    "weightGPerCm2": 0.5,
    "kgCo2ePerKg": 0.97,
    "waterM3PerKg": 0.29,
    "impactUsdPerKg": 0.62,
    "largestFactor": "water"
  },
  {
    "factorKey": "vegetable-cannelloni",
    "food": "Vegetable Cannelloni",
    "station": "24 Carrots",
    "weightGPerCm2": 2,
    "kgCo2ePerKg": 3.69,
    "waterM3PerKg": 0.883,
    "impactUsdPerKg": 2.03,
    "largestFactor": "water"
  },
  {
    "factorKey": "panzanella-salad",
    "food": "Panzanella Salad",
    "station": "24 Carrots",
    "weightGPerCm2": 0.9,
    "kgCo2ePerKg": 2.16,
    "waterM3PerKg": 0.587,
    "impactUsdPerKg": 1.29,
    "largestFactor": "water"
  },
  {
    "factorKey": "ancho-flank-steak",
    "food": "Ancho Flank Steak",
    "station": "Halal",
    "weightGPerCm2": 1.2,
    "kgCo2ePerKg": 131.69,
    "waterM3PerKg": 1.925,
    "impactUsdPerKg": 27.91,
    "largestFactor": "carbon"
  },
  {
    "factorKey": "sticky-rice",
    "food": "Sticky Rice",
    "station": "Halal",
    "weightGPerCm2": 1.6,
    "kgCo2ePerKg": 1.78,
    "waterM3PerKg": 0.899,
    "impactUsdPerKg": 1.69,
    "largestFactor": "water"
  },
  {
    "factorKey": "vegetable-stir-fry-blend",
    "food": "Vegetable Stir Fry Blend",
    "station": "Halal",
    "weightGPerCm2": 0.8,
    "kgCo2ePerKg": 0.48,
    "waterM3PerKg": 0.08,
    "impactUsdPerKg": 0.21,
    "largestFactor": "water"
  },
  {
    "factorKey": "cheese-bread",
    "food": "Cheese Bread",
    "station": "Pizziti",
    "weightGPerCm2": 0.7,
    "kgCo2ePerKg": 12.64,
    "waterM3PerKg": 3.032,
    "impactUsdPerKg": 6.95,
    "largestFactor": "water"
  },
  {
    "factorKey": "pepperoni-pizza",
    "food": "Pepperoni Pizza",
    "station": "Pizziti",
    "weightGPerCm2": 1,
    "kgCo2ePerKg": 16.06,
    "waterM3PerKg": 1.94,
    "impactUsdPerKg": 5.96,
    "largestFactor": "carbon"
  },
  {
    "factorKey": "cheese-pizza",
    "food": "Cheese Pizza",
    "station": "Pizziti",
    "weightGPerCm2": 1,
    "kgCo2ePerKg": 7.65,
    "waterM3PerKg": 1.94,
    "impactUsdPerKg": 4.36,
    "largestFactor": "water"
  },
  {
    "factorKey": "chicken-broccoli-alfredo-pizza",
    "food": "Chicken Broccoli Alfredo Pizza",
    "station": "Pizziti",
    "weightGPerCm2": 1.1,
    "kgCo2ePerKg": 8.75,
    "waterM3PerKg": 1.922,
    "impactUsdPerKg": 4.55,
    "largestFactor": "water"
  },
  {
    "factorKey": "chocolate-coconut-cream-pie",
    "food": "Chocolate Coconut Cream Pie",
    "station": "MBakery",
    "weightGPerCm2": 2.4,
    "kgCo2ePerKg": 5.55,
    "waterM3PerKg": 0.303,
    "impactUsdPerKg": 1.51,
    "largestFactor": "carbon"
  },
  {
    "factorKey": "pumpkin-pie",
    "food": "Pumpkin Pie",
    "station": "MBakery",
    "weightGPerCm2": 2.2,
    "kgCo2ePerKg": 4.52,
    "waterM3PerKg": 0.894,
    "impactUsdPerKg": 2.2,
    "largestFactor": "water"
  },
  {
    "factorKey": "snickers-brownies-with-peanuts",
    "food": "Snickers Brownies with Peanuts",
    "station": "MBakery",
    "weightGPerCm2": 2.2,
    "kgCo2ePerKg": 12.93,
    "waterM3PerKg": 1.365,
    "impactUsdPerKg": 4.5,
    "largestFactor": "carbon"
  },
  {
    "factorKey": "peppermint-white-chocolate-blondie",
    "food": "Peppermint White Chocolate Blondie",
    "station": "MBakery",
    "weightGPerCm2": 2,
    "kgCo2ePerKg": 7.27,
    "waterM3PerKg": 1.16,
    "impactUsdPerKg": 3.12,
    "largestFactor": "water"
  },
  {
    "factorKey": "golden-cake-with-chocolate-frosting",
    "food": "Golden Cake with Chocolate Frosting",
    "station": "MBakery",
    "weightGPerCm2": 1.8,
    "kgCo2ePerKg": 3.53,
    "waterM3PerKg": 0.335,
    "impactUsdPerKg": 1.17,
    "largestFactor": "carbon"
  },
  {
    "factorKey": "strawberry-shortcake-bar",
    "food": "Strawberry Shortcake Bar",
    "station": "MBakery",
    "weightGPerCm2": 1.5,
    "kgCo2ePerKg": 2.49,
    "waterM3PerKg": 0.442,
    "impactUsdPerKg": 1.14,
    "largestFactor": "water"
  }
];

/** menu_nutrition_factors.csv rows. Reported separately; never part of the score. */
export const NUTRITION_FACTORS: NutritionFactor[] = [
  {
    "factorKey": "broccoli-cheddar-soup",
    "nutrientDaysPerKg": 0.45,
    "kcalPerKg": 1207
  },
  {
    "factorKey": "baked-boneless-ham",
    "nutrientDaysPerKg": 0.38,
    "kcalPerKg": 1306
  },
  {
    "factorKey": "oven-roasted-garlic-potatoes",
    "nutrientDaysPerKg": 0.56,
    "kcalPerKg": 1012
  },
  {
    "factorKey": "baked-sweet-potatoes",
    "nutrientDaysPerKg": 1.8,
    "kcalPerKg": 900
  },
  {
    "factorKey": "roasted-cauliflower",
    "nutrientDaysPerKg": 1.09,
    "kcalPerKg": 281
  },
  {
    "factorKey": "michigan-farmers-4-bean-stew",
    "nutrientDaysPerKg": 0.58,
    "kcalPerKg": 661
  },
  {
    "factorKey": "farro",
    "nutrientDaysPerKg": 0.61,
    "kcalPerKg": 1632
  },
  {
    "factorKey": "shaved-brussel-sprouts",
    "nutrientDaysPerKg": 1.31,
    "kcalPerKg": 1306
  },
  {
    "factorKey": "vegetable-cannelloni",
    "nutrientDaysPerKg": 0.62,
    "kcalPerKg": 1625
  },
  {
    "factorKey": "panzanella-salad",
    "nutrientDaysPerKg": 0.58,
    "kcalPerKg": 1468
  },
  {
    "factorKey": "ancho-flank-steak",
    "nutrientDaysPerKg": 1.05,
    "kcalPerKg": 2025
  },
  {
    "factorKey": "sticky-rice",
    "nutrientDaysPerKg": 0.24,
    "kcalPerKg": 941
  },
  {
    "factorKey": "vegetable-stir-fry-blend",
    "nutrientDaysPerKg": 1.58,
    "kcalPerKg": 264
  },
  {
    "factorKey": "cheese-bread",
    "nutrientDaysPerKg": 0.92,
    "kcalPerKg": 4157
  },
  {
    "factorKey": "pepperoni-pizza",
    "nutrientDaysPerKg": 0.69,
    "kcalPerKg": 2708
  },
  {
    "factorKey": "cheese-pizza",
    "nutrientDaysPerKg": 0.72,
    "kcalPerKg": 2648
  },
  {
    "factorKey": "chicken-broccoli-alfredo-pizza",
    "nutrientDaysPerKg": 0.7,
    "kcalPerKg": 2356
  },
  {
    "factorKey": "chocolate-coconut-cream-pie",
    "nutrientDaysPerKg": 0.39,
    "kcalPerKg": 3183
  },
  {
    "factorKey": "pumpkin-pie",
    "nutrientDaysPerKg": 0.97,
    "kcalPerKg": 2148
  },
  {
    "factorKey": "snickers-brownies-with-peanuts",
    "nutrientDaysPerKg": 0.55,
    "kcalPerKg": 3934
  },
  {
    "factorKey": "peppermint-white-chocolate-blondie",
    "nutrientDaysPerKg": 0.41,
    "kcalPerKg": 3790
  },
  {
    "factorKey": "golden-cake-with-chocolate-frosting",
    "nutrientDaysPerKg": 0.4,
    "kcalPerKg": 3292
  },
  {
    "factorKey": "strawberry-shortcake-bar",
    "nutrientDaysPerKg": 0.55,
    "kcalPerKg": 3976
  }
];

export const WASTE_FACTOR_MENU_TEXT: WasteFactorMenuText[] = [
  {
    "factorKey": "broccoli-cheddar-soup",
    "food": "Broccoli Cheddar Soup",
    "station": "Soup",
    "visibleComponents": "creamy yellow-orange thick soup base, small dark-green to olive-green broccoli florets and stem pieces, melted cheese streaks, slightly glossy surface",
    "ingredients": "water, cheddar cheese (pasteurized milk, cheese cultures, salt, enzymes), heavy cream, broccoli, enriched wheat flour (wheat flour, malted barley flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), butter (cream, salt), onions, chicken base (chicken meat, salt, yeast extract, sugar), modified food starch, salt, spices",
    "allergens": "milk; wheat",
    "labelServingG": 227,
    "menuCo2Label": "high"
  },
  {
    "factorKey": "baked-boneless-ham",
    "food": "Baked Boneless Ham",
    "station": "Signature Maize",
    "visibleComponents": "pink to reddish-brown sliced ham cuts with caramelized glazed edges, smooth meaty grain texture, glossy surface sheen",
    "ingredients": "cured pork ham (cured with water, dextrose, salt, potassium lactate, sodium phosphates, sodium erythorbate, sodium nitrite), brown sugar glaze (brown sugar, water, spices)",
    "allergens": "pork",
    "labelServingG": 85,
    "menuCo2Label": "medium"
  },
  {
    "factorKey": "oven-roasted-garlic-potatoes",
    "food": "Oven Roasted Garlic Potatoes",
    "station": "Signature Maize",
    "visibleComponents": "roasted potato chunks and wedges with crisp golden-brown edges, blistered thin red-brown skins, flecks of minced garlic and dried green herbs",
    "ingredients": "red potatoes, canola oil, minced garlic, salt, black pepper, dried parsley",
    "allergens": null,
    "labelServingG": 85,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "baked-sweet-potatoes",
    "food": "Baked Sweet Potatoes",
    "station": "Signature Maize",
    "visibleComponents": null,
    "ingredients": null,
    "allergens": null,
    "labelServingG": null,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "roasted-cauliflower",
    "food": "Roasted Cauliflower",
    "station": "Signature Maize",
    "visibleComponents": "ivory to off-white cauliflower florets with browned roasted tips, blistered surfaces, and char marks",
    "ingredients": "cauliflower florets, vegetable cooking spray (canola oil), salt, black pepper",
    "allergens": null,
    "labelServingG": 57,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "michigan-farmers-4-bean-stew",
    "food": "Michigan Farmers 4 Bean Stew",
    "station": "24 Carrots",
    "visibleComponents": "chunky stew broth with a mix of whole kidney beans, black beans, pinto beans, and white cannellini beans, mixed with diced orange carrots, diced onions, crushed red tomatoes, and herb specks",
    "ingredients": "vegetable broth (water, carrots, celery, onions, salt), bean blend (kidney beans, black beans, pinto beans, cannellini beans), diced tomatoes in juice, onions, carrots, celery, olive oil, tomato paste, garlic, salt, oregano, thyme, black pepper",
    "allergens": null,
    "labelServingG": 180,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "farro",
    "food": "Farro",
    "station": "24 Carrots",
    "visibleComponents": "pile of plump, oval, brownish-tan cooked grain kernels with cracked ridges, semi-glossy and firm texture",
    "ingredients": "water, farro (wheat), vegetable base (salt, sugar, yeast extract, onion powder, garlic powder), salt",
    "allergens": "wheat",
    "labelServingG": 57,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "shaved-brussel-sprouts",
    "food": "Shaved Brussel Sprouts",
    "station": "24 Carrots",
    "visibleComponents": "shredded ribbon-like green and pale yellow Brussels sprout leaves, limp sauteed texture, pan-browned charred edges, glossy oil sheen",
    "ingredients": "shaved Brussels sprouts, olive oil, shallots, apple cider vinegar, maple syrup, salt, black pepper",
    "allergens": null,
    "labelServingG": 85,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "vegetable-cannelloni",
    "food": "Vegetable Cannelloni",
    "station": "24 Carrots",
    "visibleComponents": "rolled cylindrical pasta tube baked under red tomato sauce and browned melted mozzarella cheese, with visible green spinach and white ricotta curd filling at the ends",
    "ingredients": "filling (ricotta cheese [whey, milk, vinegar, salt], spinach, zucchini, carrots, mozzarella cheese, parmesan cheese, breadcrumbs [wheat flour, yeast, salt], eggs, salt, garlic, spices), pasta (durum wheat flour, water, eggs), tomato sauce (diced tomatoes, tomato puree, olive oil, onions, garlic, salt, basil), mozzarella cheese",
    "allergens": "eggs; milk; wheat",
    "labelServingG": 160,
    "menuCo2Label": "medium"
  },
  {
    "factorKey": "panzanella-salad",
    "food": "Panzanella Salad",
    "station": "24 Carrots",
    "visibleComponents": "toasted golden-brown bread cubes soaked with vinaigrette, mixed with red tomato wedges, diced green cucumbers, thin purple red onion slivers, torn dark-green basil leaves, and finely shredded parmesan",
    "ingredients": "tomatoes, rustic bread croutons (wheat flour, water, salt, yeast), olive oil, cucumbers, red onions, red wine vinegar, fresh basil, shredded parmesan cheese (pasteurized milk, cheese cultures, salt, enzymes), salt, black pepper",
    "allergens": "milk; wheat",
    "labelServingG": 233,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "ancho-flank-steak",
    "food": "Ancho Flank Steak",
    "station": "Halal",
    "visibleComponents": "diagonal slices of grilled beef steak, charred dark reddish-brown exterior crusted with chili spices, pinkish-tan fibrous interior",
    "ingredients": "beef flank steak, ancho marinade (ancho chili powder, water, lime juice, olive oil, garlic, cumin, salt, black pepper)",
    "allergens": "beef",
    "labelServingG": 94,
    "menuCo2Label": "high"
  },
  {
    "factorKey": "sticky-rice",
    "food": "Sticky Rice",
    "station": "Halal",
    "visibleComponents": "cluster of glossy, translucent to opaque white short-grain rice clumped together into a sticky mound",
    "ingredients": "glutinous sweet rice, water",
    "allergens": null,
    "labelServingG": 85,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "vegetable-stir-fry-blend",
    "food": "Vegetable Stir Fry Blend",
    "station": "Halal",
    "visibleComponents": "colorful assortment of tender-crisp cut vegetables including dark green broccoli florets, diagonal sliced orange carrots, red bell pepper strips, green snap peas, and ivory water chestnut slices coated in a clear sheen",
    "ingredients": "broccoli florets, carrots, snap peas, red bell peppers, water chestnuts, onions, stir-fry seasoning (water, vegetable broth, sesame oil, garlic, ginger, cornstarch, salt)",
    "allergens": null,
    "labelServingG": 227,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "cheese-bread",
    "food": "Cheese Bread",
    "station": "Pizziti",
    "visibleComponents": "thick rectangular bread strips with melted, bubbly golden-brown cheese top, pale inner dough, crusty bottom and edges, sprinkled dried green oregano",
    "ingredients": "dough (enriched wheat flour [wheat flour, malted barley flour, niacin, iron, thiamine mononitrate, riboflavin, folic acid], water, soybean oil, sugar, yeast, salt, egg), mozzarella cheese (pasteurized milk, cultures, salt, enzymes), garlic herb spread (butter, soybean oil, garlic, salt, dried oregano, parsley), parmesan cheese",
    "allergens": "eggs; milk; soy; wheat",
    "labelServingG": 51,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "pepperoni-pizza",
    "food": "Pepperoni Pizza",
    "station": "Pizziti",
    "visibleComponents": "triangular pizza slice with a puffy golden crust edge, melted white-and-gold cheese, sliced circular reddish-brown beef pepperoni cups with glistening orange oils, red tomato sauce underneath",
    "ingredients": "crust (enriched wheat flour [wheat flour, malted barley flour, niacin, iron, thiamine mononitrate, riboflavin, folic acid], water, soybean oil, yeast, salt, sugar, egg), low-moisture mozzarella cheese (pasteurized milk, cultures, salt, enzymes), pizza sauce (crushed tomatoes, water, salt, basil, oregano, garlic powder), beef pepperoni (beef, salt, spices, dextrose, lactic acid starter culture, paprika oleoresin, garlic powder, sodium nitrite)",
    "allergens": "beef; eggs; milk; soy; wheat",
    "labelServingG": 113,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "cheese-pizza",
    "food": "Cheese Pizza",
    "station": "Pizziti",
    "visibleComponents": "triangular pizza slice featuring a golden-brown outer crust rim, even layer of melted cream-colored mozzarella with toasted brown spots, and red sauce beneath",
    "ingredients": "crust (enriched wheat flour [wheat flour, malted barley flour, niacin, iron, thiamine mononitrate, riboflavin, folic acid], water, soybean oil, yeast, salt, sugar, egg), low-moisture mozzarella cheese (pasteurized milk, cultures, salt, enzymes), pizza sauce (crushed tomatoes, water, salt, basil, oregano, garlic powder), parmesan cheese",
    "allergens": "eggs; milk; soy; wheat",
    "labelServingG": 105,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "chicken-broccoli-alfredo-pizza",
    "food": "Chicken Broccoli Alfredo Pizza",
    "station": "Pizziti",
    "visibleComponents": "triangular pizza slice covered in creamy ivory alfredo sauce, melted mozzarella, chopped dark-green broccoli florets, and pale diced grilled chicken cubes over a browned crust",
    "ingredients": "crust (enriched wheat flour [wheat flour, malted barley flour, niacin, iron, thiamine mononitrate, riboflavin, folic acid], water, soybean oil, yeast, salt, sugar, egg), alfredo sauce (heavy cream, milk, butter, parmesan cheese, modified cornstarch, garlic, salt), mozzarella cheese (pasteurized milk, cultures, salt, enzymes), grilled chicken breast (chicken breast, water, salt), broccoli florets",
    "allergens": "eggs; milk; soy; wheat",
    "labelServingG": 132,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "chocolate-coconut-cream-pie",
    "food": "Chocolate Coconut Cream Pie",
    "station": "MBakery",
    "visibleComponents": "wedge of pie showing a dark chocolate pudding layer set in a tan oat-flour pastry crust, topped with white fluffy whipped topping and toasted golden-brown coconut flakes",
    "ingredients": "coconut cream (coconut extract, water), sugar, chocolate filling (water, sugar, cocoa powder processed with alkali, modified cornstarch, coconut oil, soy lecithin, vanilla extract [ethyl alcohol, water, vanilla bean extractives], salt), crust (enriched wheat flour, oat flour, palm oil, soybean oil, sugar, water, salt), non-dairy whipped topping (coconut oil, sugar, water), toasted coconut flakes",
    "allergens": "alcohol; coconut; oats; soy; wheat",
    "labelServingG": 142,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "pumpkin-pie",
    "food": "Pumpkin Pie",
    "station": "MBakery",
    "visibleComponents": "pie slice with smooth, dense orange-brown pumpkin custard filling bordered by a fluted, golden-baked pastry crust edge",
    "ingredients": "pumpkin puree, evaporated milk (milk, dipotassium phosphate, carrageenan, vitamin D3), crust (enriched wheat flour, palm oil, water, sugar, salt), sugar, whole eggs, brown sugar, cinnamon, ginger, nutmeg, cloves, salt",
    "allergens": "eggs; milk; wheat",
    "labelServingG": 135,
    "menuCo2Label": "medium"
  },
  {
    "factorKey": "snickers-brownies-with-peanuts",
    "food": "Snickers Brownies with Peanuts",
    "station": "MBakery",
    "visibleComponents": "dense square dark-brown fudge brownie, topped with a shiny caramel swirl, studded with halves of roasted tan peanuts and chopped chocolate candy bar pieces",
    "ingredients": "sugar, butter (cream, salt), enriched wheat flour, whole eggs, cocoa powder processed with alkali, Snickers candy pieces (milk chocolate [sugar, cocoa butter, chocolate, skim milk, lactose, milkfat, soy lecithin], peanuts, corn syrup, sugar, palm oil, skim milk), roasted peanuts, caramel (corn syrup, sweetened condensed milk, butter), soy lecithin, vanilla extract, salt",
    "allergens": "eggs; milk; peanuts; soy; tree nuts; wheat",
    "labelServingG": 91,
    "menuCo2Label": "medium"
  },
  {
    "factorKey": "peppermint-white-chocolate-blondie",
    "food": "Peppermint White Chocolate Blondie",
    "station": "MBakery",
    "visibleComponents": "square golden-tan blondie bar with visible melted creamy-white chocolate morsels, scattered with pink and red crunchy crushed candy cane specks",
    "ingredients": "brown sugar, enriched wheat flour, butter (cream, salt), whole eggs, white chocolate chips (sugar, cocoa butter, whole milk powder, soy lecithin, vanilla extract), crushed peppermint candy (sugar, corn syrup, peppermint oil, red 40), vanilla extract (alcohol, water, vanilla bean extractives), peppermint extract (alcohol, peppermint oil), baking powder, salt",
    "allergens": "alcohol; eggs; milk; soy; wheat",
    "labelServingG": 81,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "golden-cake-with-chocolate-frosting",
    "food": "Golden Cake with Chocolate Frosting",
    "station": "MBakery",
    "visibleComponents": "slice of pale golden-yellow sponge cake topped with a thick, swooped layer of glossy dark-brown chocolate frosting along the top and back",
    "ingredients": "cake (sugar, enriched wheat flour, water, soybean oil, oat flour, baking powder [sodium acid pyrophosphate, sodium bicarbonate, cornstarch, monocalcium phosphate], vanilla extract [alcohol, water, vanilla bean extractives], salt, soy lecithin), chocolate frosting (powdered sugar, palm oil shortening, soybean oil, water, cocoa processed with alkali, corn syrup, soy lecithin, vanilla extract, salt)",
    "allergens": "alcohol; oats; soy; wheat",
    "labelServingG": 130,
    "menuCo2Label": "low"
  },
  {
    "factorKey": "strawberry-shortcake-bar",
    "food": "Strawberry Shortcake Bar",
    "station": "MBakery",
    "visibleComponents": "rectangular dessert bar coated in textured pink, red, and off-white shortcake crumbs, showing a pale crumb cake base and an interior red fruit gel layer",
    "ingredients": "cake and crumble base (enriched wheat flour, sugar, oat flour, palm oil, soybean oil, dried egg whites, nonfat dry milk, soy lecithin, salt), strawberry layer (sugar, corn syrup, strawberry puree, gelatin [pork], citric acid, red 40, natural flavor), vanilla coating and crumb topping (sugar, enriched wheat flour, palm oil, dried strawberry crumbs)",
    "allergens": "eggs; milk; oats; pork; soy; wheat",
    "labelServingG": 41,
    "menuCo2Label": "low"
  }
];
